version: '3.3'
services:
  cassandra:
    image: cassandra:4.0.1
    ports:
      - 9042:9042
    # command: cassandra -f && cqlsh -f "INSERT INTO cycling.cyclist_name (id, lastname, firstname) VALUES (5b6962dd-3f90-4c93-8f61-eabfa4a803e2, 'VOS','Marianne');"
    volumes:
      - ${PWD}/config/cassandra.yaml:/etc/cassandra/cassandra.yaml
      # - ~/apps/cassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=cloudinfra